[package]
name = "server"
version = "0.1.0"
authors = ["kriston"]
edition = "2018"

[dependencies]
webrtc-unreliable = "0.5.0"
tokio = { version = "0.2", features = ["full"] }
hyper = "0.13.8"
tracing = "0.1.21"
tracing-subscriber = "0.2.14"

